### ISSUE TITLE
about  scaling

### ISSUE THREAD

**Issue by qtbgo** [m1balcerak/labels#1]
Dear Michal Balcerak,
   I have read your paper Constructing trading strategy ensembles by classifying market states. It's very interesting. And may I ask a question?
In your paper, you say "We normalise their values to [−1, 1] using local scaling by standard deviation and arctangent function", Could you give  an example or a formula on how you make this scaling.

**Comment by m1balcerak** [comment]
Hi gtbgo - please go to page 22 of https://github.com/m1balcerak/financial_labels/blob/main/related_work/master_thesis_MB.pdf The issue is explained there in details.
