### ISSUE TITLE
Feature scaling

### ISSUE THREAD

**Issue by PatCH0816** [m1balcerak/labels#2]
The feature scaling range mentioned in the paper on page 5 is defined as [-1, 1], this would indicate the use tangens hyperbolicus function, which has exactly this range. However, not the tangens hyperbolicus function is mentioned in the same sentence, but the arctangent function, which has a range of [-pi/2, pi/2]. This does not line up. Therefore the question: Which function is used and why? Which range should be prefered? Is it the  tangens hyperbolicus function with the range [-1, 1] or is it the arctangent function with the range [-pi/2, pi/2]?

**Comment by m1balcerak** [comment]
It is a scaled arctangent with some additional tricks i.e. 90% of data around a semi-linear region of it. Please go to page 22 of https://github.com/m1balcerak/financial_labels/blob/main/related_work/master_thesis_MB.pdf The issue is explained there in details.

**Comment by PatCH0816** [comment]
Perfect, thanks for your support :)
