### ISSUE TITLE
Scoring function

### ISSUE THREAD

**Issue by PatCH0816** [m1balcerak/labels#4]
In the chapter "6.2 Results - single strategy performances", the score function is given as S=MP-TP-MCIP (Small typo: MP instead of MR, which stands for monthly return). Since the past dataset contains 4 months, there are two options to compute the score.

1. Do you compute the score for each of these 4 months on their own and compute the mean afterwards?
2. Do you first compute the 4-month return and afterwards the monthly return from this result?
3. Is is some other computation, we did not think of? :)

**Comment by m1balcerak** [comment]
Thanks for pointing out the typo. It is 1).

**Comment by PatCH0816** [comment]
Thanks for the clarification :)
