### ISSUE TITLE
Strategy ensemble

### ISSUE THREAD

**Issue by PatCH0816** [m1balcerak/labels#5]
In chapter "6.3 Results - strategy ensemble performances" there are several figures with the top100, top 20, top10 and top5 strategies presented. On top of that, there is a strategy ensemble included in these figures, but it is not mentioned, how this ensemble has been computed. Since this yellow ensemble line is always around the middle of all violet strategy lines, we expect the ensemble to be the mean/median position sizes of all strategy outputs. Could you tell us, how this strategy ensemble has been computed?

**Comment by m1balcerak** [comment]
If we have N strategies then each of the them is given 1/N of the assets to manage. Effectively you get the mean. Check: _Changing strategies on the fly_ in chapter **8** for a possible modification.

**Comment by PatCH0816** [comment]
Thanks for the clarification :)
